package dao.model;
// Generated 2016-7-26 8:50:26 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TDepartment generated by hbm2java
 */
public class TDepartment implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer pid;
	private String deptNo;
	private Date createTime;
	private String creator;
	private String status;
	private String memo;
	private Set TUsers = new HashSet(0);

	public TDepartment() {
	}

	public TDepartment(String name, Integer pid, String deptNo, Date createTime, String creator, String status,
			String memo, Set TUsers) {
		this.name = name;
		this.pid = pid;
		this.deptNo = deptNo;
		this.createTime = createTime;
		this.creator = creator;
		this.status = status;
		this.memo = memo;
		this.TUsers = TUsers;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(String deptNo) {
		this.deptNo = deptNo;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Set getTUsers() {
		return this.TUsers;
	}

	public void setTUsers(Set TUsers) {
		this.TUsers = TUsers;
	}

}
