package dao.model;
// Generated 2016-8-23 9:45:27 by Hibernate Tools 4.3.4.Final

/**
 * TEnumbank generated by hbm2java
 */
public class TEnumbank implements java.io.Serializable {

	private Integer id;
	private String enumtypeid;
	private String enumtypename;
	private String enumid;
	private String enumvalue;
	private Byte flag;
	private String remark;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEnumtypeid() {
		return enumtypeid;
	}

	public void setEnumtypeid(String enumtypeid) {
		this.enumtypeid = enumtypeid;
	}

	public String getEnumtypename() {
		return enumtypename;
	}

	public void setEnumtypename(String enumtypename) {
		this.enumtypename = enumtypename;
	}

	public String getEnumid() {
		return enumid;
	}

	public void setEnumid(String enumid) {
		this.enumid = enumid;
	}

	public String getEnumvalue() {
		return enumvalue;
	}

	public void setEnumvalue(String enumvalue) {
		this.enumvalue = enumvalue;
	}

	public Byte getFlag() {
		return flag;
	}

	public void setFlag(Byte flag) {
		this.flag = flag;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
