package dao.model;
// Generated 2016-8-24 20:31:25 by Hibernate Tools 4.3.1.Final

/**
 * TEnumbank generated by hbm2java
 */
public class TEnumbank implements java.io.Serializable {

	private Integer id;
	private String typeId;
	private String typeName;
	private String enumId;
	private String enumValue;
	private Character state;
	private String remark;

	public TEnumbank() {
	}

	public TEnumbank(String typeId, String typeName, String enumId, String enumValue) {
		this.typeId = typeId;
		this.typeName = typeName;
		this.enumId = enumId;
		this.enumValue = enumValue;
	}

	public TEnumbank(String typeId, String typeName, String enumId, String enumValue, Character state, String remark) {
		this.typeId = typeId;
		this.typeName = typeName;
		this.enumId = enumId;
		this.enumValue = enumValue;
		this.state = state;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTypeId() {
		return this.typeId;
	}

	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public String getEnumId() {
		return this.enumId;
	}

	public void setEnumId(String enumId) {
		this.enumId = enumId;
	}

	public String getEnumValue() {
		return this.enumValue;
	}

	public void setEnumValue(String enumValue) {
		this.enumValue = enumValue;
	}

	public Character getState() {
		return this.state;
	}

	public void setState(Character state) {
		this.state = state;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
