package dao.model;
// Generated 2016-7-15 8:46:05 by Hibernate Tools 4.3.1.Final

/**
 * TEnumbank generated by hbm2java
 */
public class TEnumbank implements java.io.Serializable {

	private Integer id;
	private String enumtypeid;
	private String enumtypename;
	private String enumid;
	private String enumvalue;
	private Byte flag;
	private String remark;

	public TEnumbank() {
	}

	public TEnumbank(String enumtypeid, String enumtypename, String enumid, String enumvalue, Byte flag,
			String remark) {
		this.enumtypeid = enumtypeid;
		this.enumtypename = enumtypename;
		this.enumid = enumid;
		this.enumvalue = enumvalue;
		this.flag = flag;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEnumtypeid() {
		return this.enumtypeid;
	}

	public void setEnumtypeid(String enumtypeid) {
		this.enumtypeid = enumtypeid;
	}

	public String getEnumtypename() {
		return this.enumtypename;
	}

	public void setEnumtypename(String enumtypename) {
		this.enumtypename = enumtypename;
	}

	public String getEnumid() {
		return this.enumid;
	}

	public void setEnumid(String enumid) {
		this.enumid = enumid;
	}

	public String getEnumvalue() {
		return this.enumvalue;
	}

	public void setEnumvalue(String enumvalue) {
		this.enumvalue = enumvalue;
	}

	public Byte getFlag() {
		return this.flag;
	}

	public void setFlag(Byte flag) {
		this.flag = flag;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
