package dao.model;
// Generated 2016-7-25 10:41:41 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TFile generated by hbm2java
 */
public class TFile implements java.io.Serializable {

	private Integer id;
	private String fileDesc;
	private String fileName;
	private String fileType;
	private Integer fileSize;
	private String filePath;
	private Integer createor;
	private Date createTime;
	private String memo;

	public TFile() {
	}

	public TFile(String fileName, String filePath) {
		this.fileName = fileName;
		this.filePath = filePath;
	}

	public TFile(String fileDesc, String fileName, String fileType, Integer fileSize, String filePath, Integer createor,
			Date createTime, String memo) {
		this.fileDesc = fileDesc;
		this.fileName = fileName;
		this.fileType = fileType;
		this.fileSize = fileSize;
		this.filePath = filePath;
		this.createor = createor;
		this.createTime = createTime;
		this.memo = memo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFileDesc() {
		return this.fileDesc;
	}

	public void setFileDesc(String fileDesc) {
		this.fileDesc = fileDesc;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	public Integer getFileSize() {
		return this.fileSize;
	}

	public void setFileSize(Integer fileSize) {
		this.fileSize = fileSize;
	}

	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public Integer getCreateor() {
		return this.createor;
	}

	public void setCreateor(Integer createor) {
		this.createor = createor;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
