package dao.model;
// Generated 2016-8-24 20:31:25 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TNews generated by hbm2java
 */
public class TNews implements java.io.Serializable {

	private Integer id;
	private TNewsType TNewsType;
	private String title;
	private String publisher;
	private String content;
	private String source;
	private String imageUrl;
	private String summary;
	private Integer creator;
	private Date createTime;
	private Integer modifier;
	private Date modifyTime;
	private String state;
	private String remark;

	public TNews() {
	}

	public TNews(TNewsType TNewsType, String title, String publisher, String content, String state) {
		this.TNewsType = TNewsType;
		this.title = title;
		this.publisher = publisher;
		this.content = content;
		this.state = state;
	}

	public TNews(TNewsType TNewsType, String title, String publisher, String content, String source, String imageUrl,
			String summary, Integer creator, Date createTime, Integer modifier, Date modifyTime, String state,
			String remark) {
		this.TNewsType = TNewsType;
		this.title = title;
		this.publisher = publisher;
		this.content = content;
		this.source = source;
		this.imageUrl = imageUrl;
		this.summary = summary;
		this.creator = creator;
		this.createTime = createTime;
		this.modifier = modifier;
		this.modifyTime = modifyTime;
		this.state = state;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TNewsType getTNewsType() {
		return this.TNewsType;
	}

	public void setTNewsType(TNewsType TNewsType) {
		this.TNewsType = TNewsType;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public Integer getCreator() {
		return this.creator;
	}

	public void setCreator(Integer creator) {
		this.creator = creator;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getModifier() {
		return this.modifier;
	}

	public void setModifier(Integer modifier) {
		this.modifier = modifier;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
