package dao.model;
// Generated 2016-8-24 20:31:25 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TNewsType generated by hbm2java
 */
public class TNewsType implements java.io.Serializable {

	private Integer id;
	private String typeName;
	private int creator;
	private Date createTime;
	private Integer modifier;
	private Date modifyTime;
	private int sort;
	private String state;
	private String remark;
	private Set TNewses = new HashSet(0);
	private Set TNewses_1 = new HashSet(0);

	public TNewsType() {
	}

	public TNewsType(String typeName, int creator, Date createTime, int sort, String state) {
		this.typeName = typeName;
		this.creator = creator;
		this.createTime = createTime;
		this.sort = sort;
		this.state = state;
	}

	public TNewsType(String typeName, int creator, Date createTime, Integer modifier, Date modifyTime, int sort,
			String state, String remark, Set TNewses, Set TNewses_1) {
		this.typeName = typeName;
		this.creator = creator;
		this.createTime = createTime;
		this.modifier = modifier;
		this.modifyTime = modifyTime;
		this.sort = sort;
		this.state = state;
		this.remark = remark;
		this.TNewses = TNewses;
		this.TNewses_1 = TNewses_1;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public int getCreator() {
		return this.creator;
	}

	public void setCreator(int creator) {
		this.creator = creator;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getModifier() {
		return this.modifier;
	}

	public void setModifier(Integer modifier) {
		this.modifier = modifier;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public int getSort() {
		return this.sort;
	}

	public void setSort(int sort) {
		this.sort = sort;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set getTNewses() {
		return this.TNewses;
	}

	public void setTNewses(Set TNewses) {
		this.TNewses = TNewses;
	}

	public Set getTNewses_1() {
		return this.TNewses_1;
	}

	public void setTNewses_1(Set TNewses_1) {
		this.TNewses_1 = TNewses_1;
	}

}
