package dao.model;
// Generated 2016-6-22 14:06:48 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TNews generated by hbm2java
 */
public class TNews implements java.io.Serializable {

	private Integer id;
	private TNewsType TNewsType;
	private String title;
	private String publisher;
	private String content;
	private String source;
	private String imageUrl;
	private String summary;
	private Date createTime;
	private Date modifyTime;
	private String status;

	public TNews() {
	}

	public TNews(TNewsType TNewsType, String title, String publisher, String content, String status) {
		this.TNewsType = TNewsType;
		this.title = title;
		this.publisher = publisher;
		this.content = content;
		this.status = status;
	}

	public TNews(TNewsType TNewsType, String title, String publisher, String content, String source, String imageUrl,
			String summary, Date createTime, Date modifyTime, String status) {
		this.TNewsType = TNewsType;
		this.title = title;
		this.publisher = publisher;
		this.content = content;
		this.source = source;
		this.imageUrl = imageUrl;
		this.summary = summary;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TNewsType getTNewsType() {
		return this.TNewsType;
	}

	public void setTNewsType(TNewsType TNewsType) {
		this.TNewsType = TNewsType;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
