package dao.model;
// Generated 2016-8-23 9:45:27 by Hibernate Tools 4.3.4.Final

/**
 * TPrivilegesMatrix generated by hbm2java
 */
public class TPrivilegesMatrix implements java.io.Serializable {

	private Integer id;
	private TPrivileges TPrivileges;
	private TRole TRole;
	private boolean isCreate;
	private boolean isDelete;
	private boolean isModify;
	private boolean isSelect;
	private boolean isPrint;
	private boolean isImport;
	private boolean isExport;
	private String remark;

	public TPrivilegesMatrix() {
	}

	public TPrivilegesMatrix(TPrivileges TPrivileges, TRole TRole, boolean isCreate, boolean isDelete, boolean isModify,
			boolean isSelect, boolean isPrint, boolean isImport, boolean isExport) {
		this.TPrivileges = TPrivileges;
		this.TRole = TRole;
		this.isCreate = isCreate;
		this.isDelete = isDelete;
		this.isModify = isModify;
		this.isSelect = isSelect;
		this.isPrint = isPrint;
		this.isImport = isImport;
		this.isExport = isExport;
	}

	public TPrivilegesMatrix(TPrivileges TPrivileges, TRole TRole, boolean isCreate, boolean isDelete, boolean isModify,
			boolean isSelect, boolean isPrint, boolean isImport, boolean isExport, String remark) {
		this.TPrivileges = TPrivileges;
		this.TRole = TRole;
		this.isCreate = isCreate;
		this.isDelete = isDelete;
		this.isModify = isModify;
		this.isSelect = isSelect;
		this.isPrint = isPrint;
		this.isImport = isImport;
		this.isExport = isExport;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TPrivileges getTPrivileges() {
		return this.TPrivileges;
	}

	public void setTPrivileges(TPrivileges TPrivileges) {
		this.TPrivileges = TPrivileges;
	}

	public TRole getTRole() {
		return this.TRole;
	}

	public void setTRole(TRole TRole) {
		this.TRole = TRole;
	}

	public boolean isIsCreate() {
		return this.isCreate;
	}

	public void setIsCreate(boolean isCreate) {
		this.isCreate = isCreate;
	}

	public boolean isIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(boolean isDelete) {
		this.isDelete = isDelete;
	}

	public boolean isIsModify() {
		return this.isModify;
	}

	public void setIsModify(boolean isModify) {
		this.isModify = isModify;
	}

	public boolean isIsSelect() {
		return this.isSelect;
	}

	public void setIsSelect(boolean isSelect) {
		this.isSelect = isSelect;
	}

	public boolean isIsPrint() {
		return this.isPrint;
	}

	public void setIsPrint(boolean isPrint) {
		this.isPrint = isPrint;
	}

	public boolean isIsImport() {
		return this.isImport;
	}

	public void setIsImport(boolean isImport) {
		this.isImport = isImport;
	}

	public boolean isIsExport() {
		return this.isExport;
	}

	public void setIsExport(boolean isExport) {
		this.isExport = isExport;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
