package dao.model;
// Generated 2016-7-25 10:41:41 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TPriviledges generated by hbm2java
 */
public class TPriviledges implements java.io.Serializable {

	private Integer id;
	private String name;
	private String url;
	private String status;
	private Date createTime;
	private Date modifyTime;
	private Integer pid;
	private String icon;
	private Integer creator;
	private String memo;
	private Boolean isParent;
	private Set TRolePriviledgeses = new HashSet(0);
	private Set TPriviledgesMatrixes = new HashSet(0);
	private Set TPriviledgesMatrixes_1 = new HashSet(0);
	private Set TRolePriviledgeses_1 = new HashSet(0);

	public TPriviledges() {
	}

	public TPriviledges(String url, String status) {
		this.url = url;
		this.status = status;
	}

	public TPriviledges(String name, String url, String status, Date createTime, Date modifyTime, Integer pid,
			String icon, Integer creator, String memo, Boolean isParent, Set TRolePriviledgeses,
			Set TPriviledgesMatrixes, Set TPriviledgesMatrixes_1, Set TRolePriviledgeses_1) {
		this.name = name;
		this.url = url;
		this.status = status;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
		this.pid = pid;
		this.icon = icon;
		this.creator = creator;
		this.memo = memo;
		this.isParent = isParent;
		this.TRolePriviledgeses = TRolePriviledgeses;
		this.TPriviledgesMatrixes = TPriviledgesMatrixes;
		this.TPriviledgesMatrixes_1 = TPriviledgesMatrixes_1;
		this.TRolePriviledgeses_1 = TRolePriviledgeses_1;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public Integer getCreator() {
		return this.creator;
	}

	public void setCreator(Integer creator) {
		this.creator = creator;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Boolean getIsParent() {
		return this.isParent;
	}

	public void setIsParent(Boolean isParent) {
		this.isParent = isParent;
	}

	public Set getTRolePriviledgeses() {
		return this.TRolePriviledgeses;
	}

	public void setTRolePriviledgeses(Set TRolePriviledgeses) {
		this.TRolePriviledgeses = TRolePriviledgeses;
	}

	public Set getTPriviledgesMatrixes() {
		return this.TPriviledgesMatrixes;
	}

	public void setTPriviledgesMatrixes(Set TPriviledgesMatrixes) {
		this.TPriviledgesMatrixes = TPriviledgesMatrixes;
	}

	public Set getTPriviledgesMatrixes_1() {
		return this.TPriviledgesMatrixes_1;
	}

	public void setTPriviledgesMatrixes_1(Set TPriviledgesMatrixes_1) {
		this.TPriviledgesMatrixes_1 = TPriviledgesMatrixes_1;
	}

	public Set getTRolePriviledgeses_1() {
		return this.TRolePriviledgeses_1;
	}

	public void setTRolePriviledgeses_1(Set TRolePriviledgeses_1) {
		this.TRolePriviledgeses_1 = TRolePriviledgeses_1;
	}

}
