package dao.model;
// Generated 2016-8-24 20:31:25 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TPrivileges generated by hbm2java
 */
public class TPrivileges implements java.io.Serializable {

	private Integer id;
	private String privilegesName;
	private String url;
	private String target;
	private Integer pid;
	private String icon;
	private Integer creator;
	private Date createTime;
	private Integer modifier;
	private Date modifyTime;
	private String state;
	private String remark;
	private Set TRolePrivilegeses = new HashSet(0);
	private Set TRolePrivilegeses_1 = new HashSet(0);
	private Set TPrivilegesMatrixes = new HashSet(0);
	private Set TPrivilegesMatrixes_1 = new HashSet(0);

	public TPrivileges() {
	}

	public TPrivileges(String url, String state) {
		this.url = url;
		this.state = state;
	}

	public TPrivileges(String privilegesName, String url, String target, Integer pid, String icon, Integer creator,
			Date createTime, Integer modifier, Date modifyTime, String state, String remark, Set TRolePrivilegeses,
			Set TRolePrivilegeses_1, Set TPrivilegesMatrixes, Set TPrivilegesMatrixes_1) {
		this.privilegesName = privilegesName;
		this.url = url;
		this.target = target;
		this.pid = pid;
		this.icon = icon;
		this.creator = creator;
		this.createTime = createTime;
		this.modifier = modifier;
		this.modifyTime = modifyTime;
		this.state = state;
		this.remark = remark;
		this.TRolePrivilegeses = TRolePrivilegeses;
		this.TRolePrivilegeses_1 = TRolePrivilegeses_1;
		this.TPrivilegesMatrixes = TPrivilegesMatrixes;
		this.TPrivilegesMatrixes_1 = TPrivilegesMatrixes_1;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPrivilegesName() {
		return this.privilegesName;
	}

	public void setPrivilegesName(String privilegesName) {
		this.privilegesName = privilegesName;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public Integer getCreator() {
		return this.creator;
	}

	public void setCreator(Integer creator) {
		this.creator = creator;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getModifier() {
		return this.modifier;
	}

	public void setModifier(Integer modifier) {
		this.modifier = modifier;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set getTRolePrivilegeses() {
		return this.TRolePrivilegeses;
	}

	public void setTRolePrivilegeses(Set TRolePrivilegeses) {
		this.TRolePrivilegeses = TRolePrivilegeses;
	}

	public Set getTRolePrivilegeses_1() {
		return this.TRolePrivilegeses_1;
	}

	public void setTRolePrivilegeses_1(Set TRolePrivilegeses_1) {
		this.TRolePrivilegeses_1 = TRolePrivilegeses_1;
	}

	public Set getTPrivilegesMatrixes() {
		return this.TPrivilegesMatrixes;
	}

	public void setTPrivilegesMatrixes(Set TPrivilegesMatrixes) {
		this.TPrivilegesMatrixes = TPrivilegesMatrixes;
	}

	public Set getTPrivilegesMatrixes_1() {
		return this.TPrivilegesMatrixes_1;
	}

	public void setTPrivilegesMatrixes_1(Set TPrivilegesMatrixes_1) {
		this.TPrivilegesMatrixes_1 = TPrivilegesMatrixes_1;
	}

}
