package dao.model;
// Generated 2016-7-26 8:50:26 by Hibernate Tools 4.3.1.Final

/**
 * TPriviledgesMatrix generated by hbm2java
 */
public class TPriviledgesMatrix implements java.io.Serializable {

	private Integer id;
	private TPriviledges TPriviledges;
	private TRole TRole;
	private boolean iscreate;
	private boolean isdelete;
	private boolean ismodify;
	private boolean isselect;
	private boolean isprint;
	private boolean isimport;
	private boolean isexport;
	private String memo;

	public TPriviledgesMatrix() {
	}

	public TPriviledgesMatrix(TPriviledges TPriviledges, TRole TRole, boolean iscreate, boolean isdelete,
			boolean ismodify, boolean isselect, boolean isprint, boolean isimport, boolean isexport) {
		this.TPriviledges = TPriviledges;
		this.TRole = TRole;
		this.iscreate = iscreate;
		this.isdelete = isdelete;
		this.ismodify = ismodify;
		this.isselect = isselect;
		this.isprint = isprint;
		this.isimport = isimport;
		this.isexport = isexport;
	}

	public TPriviledgesMatrix(TPriviledges TPriviledges, TRole TRole, boolean iscreate, boolean isdelete,
			boolean ismodify, boolean isselect, boolean isprint, boolean isimport, boolean isexport, String memo) {
		this.TPriviledges = TPriviledges;
		this.TRole = TRole;
		this.iscreate = iscreate;
		this.isdelete = isdelete;
		this.ismodify = ismodify;
		this.isselect = isselect;
		this.isprint = isprint;
		this.isimport = isimport;
		this.isexport = isexport;
		this.memo = memo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TPriviledges getTPriviledges() {
		return this.TPriviledges;
	}

	public void setTPriviledges(TPriviledges TPriviledges) {
		this.TPriviledges = TPriviledges;
	}

	public TRole getTRole() {
		return this.TRole;
	}

	public void setTRole(TRole TRole) {
		this.TRole = TRole;
	}

	public boolean isIscreate() {
		return this.iscreate;
	}

	public void setIscreate(boolean iscreate) {
		this.iscreate = iscreate;
	}

	public boolean isIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(boolean isdelete) {
		this.isdelete = isdelete;
	}

	public boolean isIsmodify() {
		return this.ismodify;
	}

	public void setIsmodify(boolean ismodify) {
		this.ismodify = ismodify;
	}

	public boolean isIsselect() {
		return this.isselect;
	}

	public void setIsselect(boolean isselect) {
		this.isselect = isselect;
	}

	public boolean isIsprint() {
		return this.isprint;
	}

	public void setIsprint(boolean isprint) {
		this.isprint = isprint;
	}

	public boolean isIsimport() {
		return this.isimport;
	}

	public void setIsimport(boolean isimport) {
		this.isimport = isimport;
	}

	public boolean isIsexport() {
		return this.isexport;
	}

	public void setIsexport(boolean isexport) {
		this.isexport = isexport;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
