package dao.model;
// Generated 2016-7-26 8:50:26 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TRole generated by hbm2java
 */
public class TRole implements java.io.Serializable {

	private Integer id;
	private String name;
	private Date createTime;
	private Date modifyTime;
	private String status;
	private String memo;
	private Set TRolePriviledgeses = new HashSet(0);
	private Set TPriviledgesMatrixes = new HashSet(0);
	private Set TPriviledgesMatrixes_1 = new HashSet(0);
	private Set TUserRoles = new HashSet(0);
	private Set TRolePriviledgeses_1 = new HashSet(0);

	public TRole() {
	}

	public TRole(String name, Date createTime) {
		this.name = name;
		this.createTime = createTime;
	}

	public TRole(String name, Date createTime, Date modifyTime, String status, String memo, Set TRolePriviledgeses,
			Set TPriviledgesMatrixes, Set TPriviledgesMatrixes_1, Set TUserRoles, Set TRolePriviledgeses_1) {
		this.name = name;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
		this.status = status;
		this.memo = memo;
		this.TRolePriviledgeses = TRolePriviledgeses;
		this.TPriviledgesMatrixes = TPriviledgesMatrixes;
		this.TPriviledgesMatrixes_1 = TPriviledgesMatrixes_1;
		this.TUserRoles = TUserRoles;
		this.TRolePriviledgeses_1 = TRolePriviledgeses_1;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Set getTRolePriviledgeses() {
		return this.TRolePriviledgeses;
	}

	public void setTRolePriviledgeses(Set TRolePriviledgeses) {
		this.TRolePriviledgeses = TRolePriviledgeses;
	}

	public Set getTPriviledgesMatrixes() {
		return this.TPriviledgesMatrixes;
	}

	public void setTPriviledgesMatrixes(Set TPriviledgesMatrixes) {
		this.TPriviledgesMatrixes = TPriviledgesMatrixes;
	}

	public Set getTPriviledgesMatrixes_1() {
		return this.TPriviledgesMatrixes_1;
	}

	public void setTPriviledgesMatrixes_1(Set TPriviledgesMatrixes_1) {
		this.TPriviledgesMatrixes_1 = TPriviledgesMatrixes_1;
	}

	public Set getTUserRoles() {
		return this.TUserRoles;
	}

	public void setTUserRoles(Set TUserRoles) {
		this.TUserRoles = TUserRoles;
	}

	public Set getTRolePriviledgeses_1() {
		return this.TRolePriviledgeses_1;
	}

	public void setTRolePriviledgeses_1(Set TRolePriviledgeses_1) {
		this.TRolePriviledgeses_1 = TRolePriviledgeses_1;
	}

}
