package dao.model;
// Generated 2016-8-24 20:31:25 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TRole generated by hbm2java
 */
public class TRole implements java.io.Serializable {

	private Integer id;
	private String roleName;
	private Integer creator;
	private Date createTime;
	private Integer modifier;
	private Date modifyTime;
	private String state;
	private String remark;
	private Set TRolePrivilegeses = new HashSet(0);
	private Set TPrivilegesMatrixes = new HashSet(0);
	private Set TPrivilegesMatrixes_1 = new HashSet(0);
	private Set TUserRoles = new HashSet(0);
	private Set TRolePrivilegeses_1 = new HashSet(0);

	public TRole() {
	}

	public TRole(String roleName, Date createTime) {
		this.roleName = roleName;
		this.createTime = createTime;
	}

	public TRole(String roleName, Integer creator, Date createTime, Integer modifier, Date modifyTime, String state,
			String remark, Set TRolePrivilegeses, Set TPrivilegesMatrixes, Set TPrivilegesMatrixes_1, Set TUserRoles,
			Set TRolePrivilegeses_1) {
		this.roleName = roleName;
		this.creator = creator;
		this.createTime = createTime;
		this.modifier = modifier;
		this.modifyTime = modifyTime;
		this.state = state;
		this.remark = remark;
		this.TRolePrivilegeses = TRolePrivilegeses;
		this.TPrivilegesMatrixes = TPrivilegesMatrixes;
		this.TPrivilegesMatrixes_1 = TPrivilegesMatrixes_1;
		this.TUserRoles = TUserRoles;
		this.TRolePrivilegeses_1 = TRolePrivilegeses_1;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Integer getCreator() {
		return this.creator;
	}

	public void setCreator(Integer creator) {
		this.creator = creator;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getModifier() {
		return this.modifier;
	}

	public void setModifier(Integer modifier) {
		this.modifier = modifier;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set getTRolePrivilegeses() {
		return this.TRolePrivilegeses;
	}

	public void setTRolePrivilegeses(Set TRolePrivilegeses) {
		this.TRolePrivilegeses = TRolePrivilegeses;
	}

	public Set getTPrivilegesMatrixes() {
		return this.TPrivilegesMatrixes;
	}

	public void setTPrivilegesMatrixes(Set TPrivilegesMatrixes) {
		this.TPrivilegesMatrixes = TPrivilegesMatrixes;
	}

	public Set getTPrivilegesMatrixes_1() {
		return this.TPrivilegesMatrixes_1;
	}

	public void setTPrivilegesMatrixes_1(Set TPrivilegesMatrixes_1) {
		this.TPrivilegesMatrixes_1 = TPrivilegesMatrixes_1;
	}

	public Set getTUserRoles() {
		return this.TUserRoles;
	}

	public void setTUserRoles(Set TUserRoles) {
		this.TUserRoles = TUserRoles;
	}

	public Set getTRolePrivilegeses_1() {
		return this.TRolePrivilegeses_1;
	}

	public void setTRolePrivilegeses_1(Set TRolePrivilegeses_1) {
		this.TRolePrivilegeses_1 = TRolePrivilegeses_1;
	}

}
