package dao.model;
// Generated 2016-8-23 9:45:27 by Hibernate Tools 4.3.4.Final

/**
 * TRolePrivileges generated by hbm2java
 */
public class TRolePrivileges implements java.io.Serializable {

	private Integer id;
	private TPrivileges TPrivileges;
	private TRole TRole;

	public TRolePrivileges() {
	}

	public TRolePrivileges(TPrivileges TPrivileges, TRole TRole) {
		this.TPrivileges = TPrivileges;
		this.TRole = TRole;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TPrivileges getTPrivileges() {
		return this.TPrivileges;
	}

	public void setTPrivileges(TPrivileges TPrivileges) {
		this.TPrivileges = TPrivileges;
	}

	public TRole getTRole() {
		return this.TRole;
	}

	public void setTRole(TRole TRole) {
		this.TRole = TRole;
	}

}
