package dao.model;
// Generated 2016-8-24 20:31:25 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TUser generated by hbm2java
 */
public class TUser implements java.io.Serializable {

	private Integer id;
	private TDepartment TDepartment;
	private String userName;
	private String sex;
	private String userAccount;
	private String password;
	private String email;
	private String mobile;
	private Integer creator;
	private Date createTime;
	private Integer modifier;
	private Date modifyTime;
	private String headImage;
	private Date loginDate;
	private String loginIp;
	private String state;
	private String remark;
	private Set TUserRoles = new HashSet(0);

	public TUser() {
	}

	public TUser(String userName, String sex, String userAccount, String password, Date createTime) {
		this.userName = userName;
		this.sex = sex;
		this.userAccount = userAccount;
		this.password = password;
		this.createTime = createTime;
	}

	public TUser(TDepartment TDepartment, String userName, String sex, String userAccount, String password,
			String email, String mobile, Integer creator, Date createTime, Integer modifier, Date modifyTime,
			String headImage, Date loginDate, String loginIp, String state, String remark, Set TUserRoles) {
		this.TDepartment = TDepartment;
		this.userName = userName;
		this.sex = sex;
		this.userAccount = userAccount;
		this.password = password;
		this.email = email;
		this.mobile = mobile;
		this.creator = creator;
		this.createTime = createTime;
		this.modifier = modifier;
		this.modifyTime = modifyTime;
		this.headImage = headImage;
		this.loginDate = loginDate;
		this.loginIp = loginIp;
		this.state = state;
		this.remark = remark;
		this.TUserRoles = TUserRoles;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TDepartment getTDepartment() {
		return this.TDepartment;
	}

	public void setTDepartment(TDepartment TDepartment) {
		this.TDepartment = TDepartment;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(String userAccount) {
		this.userAccount = userAccount;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public Integer getCreator() {
		return this.creator;
	}

	public void setCreator(Integer creator) {
		this.creator = creator;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getModifier() {
		return this.modifier;
	}

	public void setModifier(Integer modifier) {
		this.modifier = modifier;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getHeadImage() {
		return this.headImage;
	}

	public void setHeadImage(String headImage) {
		this.headImage = headImage;
	}

	public Date getLoginDate() {
		return this.loginDate;
	}

	public void setLoginDate(Date loginDate) {
		this.loginDate = loginDate;
	}

	public String getLoginIp() {
		return this.loginIp;
	}

	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set getTUserRoles() {
		return this.TUserRoles;
	}

	public void setTUserRoles(Set TUserRoles) {
		this.TUserRoles = TUserRoles;
	}

}
