package dao.model;
// Generated 2016-6-22 14:06:48 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TUser generated by hbm2java
 */
public class TUser implements java.io.Serializable {

	private Integer id;
	private String userName;
	private String sex;
	private String userAccount;
	private String password;
	private String status;
	private Integer creator;
	private Date createTime;
	private Integer modifier;
	private Date modifyTime;
	private String headImage;
	private String memo;
	private Set TUserRoles = new HashSet(0);
	private Set TUserRoles_1 = new HashSet(0);

	public TUser() {
	}

	public TUser(String userName, String sex, String userAccount, String password, Date createTime) {
		this.userName = userName;
		this.sex = sex;
		this.userAccount = userAccount;
		this.password = password;
		this.createTime = createTime;
	}

	public TUser(String userName, String sex, String userAccount, String password, String status, Integer creator,
			Date createTime, Integer modifier, Date modifyTime, String headImage, String memo, Set TUserRoles,
			Set TUserRoles_1) {
		this.userName = userName;
		this.sex = sex;
		this.userAccount = userAccount;
		this.password = password;
		this.status = status;
		this.creator = creator;
		this.createTime = createTime;
		this.modifier = modifier;
		this.modifyTime = modifyTime;
		this.headImage = headImage;
		this.memo = memo;
		this.TUserRoles = TUserRoles;
		this.TUserRoles_1 = TUserRoles_1;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(String userAccount) {
		this.userAccount = userAccount;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getCreator() {
		return this.creator;
	}

	public void setCreator(Integer creator) {
		this.creator = creator;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getModifier() {
		return this.modifier;
	}

	public void setModifier(Integer modifier) {
		this.modifier = modifier;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getHeadImage() {
		return this.headImage;
	}

	public void setHeadImage(String headImage) {
		this.headImage = headImage;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Set getTUserRoles() {
		return this.TUserRoles;
	}

	public void setTUserRoles(Set TUserRoles) {
		this.TUserRoles = TUserRoles;
	}

	public Set getTUserRoles_1() {
		return this.TUserRoles_1;
	}

	public void setTUserRoles_1(Set TUserRoles_1) {
		this.TUserRoles_1 = TUserRoles_1;
	}

}
